### ISSUE TITLE
Upgrading from 4.0.1 to 5.3.1 breaks generic method UnityContainer.Resolve<T>

### ISSUE THREAD

**Issue by alesspan** [unitycontainer/unity#159]
I'm currently using type registration with configuration file by means of MapTo xml element and by specifying LifecycleManager (PerThreadLifetimeManager, Singleton, etc...) and constructor parameters and I'd like to continue Resolving by type only without using "name" specification.
Is that still possible? 
Or what kind of changes I need to implement?

regards,
Alessandro

**Comment by ENikS** [comment]
Would help If you could provide code sample where all these failing

**Comment by alesspan** [comment]
yes,
here the code failing that simply invokes UnityContainer.Resolve<MyInterface>() and after upgrade it doesn't compile with the error:
"The non-generic method 'UnityContainer.Resolve(Type, string, params ResolverOverride[])' cannot be used with type arguments"

The configuration excerpt and I'd like to have still working is:

  <configSections>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration" />
  </configSections>
  <unity>
    <container>
            <register type="Interfaces.MyInterface, Interfaces" mapTo="Implementation.MyInterfaceImpl, Implementation">
        <lifetime type="PerThreadLifetimeManager" />
        <constructor>
          <param name="param1" value="param1Value"/>
          <param name="param2" value="param2Value"/>
        </constructor>
      </register>
    </container>
  </unity>


regards,
Alessandro

**Comment by alesspan** [comment]
configuration was stripped by saving my reply.
Trying with proper html escaping.

  &lt;configSections&gt;
    &lt;section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration" /&gt;
  &lt;/configSections&gt;
  &lt;unity&gt;
    &lt;container&gt;
      &lt;register type="Interfaces.MyInterface, Interfaces" mapTo="Implementation.MyInterfaceImpl, Implementation"&gt;
        &lt;lifetime type="PerThreadLifetimeManager" /&gt;
        &lt;constructor&gt;
          &lt;param name="param1" value="param2Value"/&gt;
          &lt;param name="param2" value="param2Value"/&gt;
        &lt;/constructor&gt;
      &lt;/register&gt;
    &lt;/container&gt;
  &lt;/unity&gt;

**Comment by ENikS** [comment]
Try:
 &lt;configSections&gt;
    &lt;section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Unity.Configuration" /&gt;
  ...

**Comment by alesspan** [comment]
I'm sorry, but I noticed even the method mentioned has been stripped out by angular parenthesis so I need to rephrase the issue.
The issue is that after upgrade to 5.3.1 the compilation fails, with error already mentioned before, in the line UnityContainer.Resolve&lt;MyInterface&gt;()

I already fixed all namespaces but this method signature change prevent me to use "legacy resolution way".
I'd like to continue using the same "legacy" way to resolve types, without needing to use the overload with "name" parameter.
Is there a workaround to obtain the same behavior?

About the configuration, I just wanna be ensured it will work at the same way as before. It's was not the focus of the issue.

many thanks

**Comment by ENikS** [comment]
If you change namespaces correctly it should work exactly as before. We have about 1300 tests still passing with all legacy syntax. Check [this project](https://github.com/unitycontainer/configuration/tree/master/tests) for samples. 

Unfortunately documentation is still not there so you would have to do it by example.

**Comment by tg123** [comment]
```

                container.RegisterType<IX, X>("x", new ContainerControlledLifetimeManager());
                var x = container.Resolve<X>("x");

                // true for 4.0.1  false for 5.3.1
                Console.WriteLine(x == container.Resolve<X>("x"));

```

**Comment by ENikS** [comment]
Yes. Think about it. You are registering **IX** with name "x" as container controlled instance of X. Once resolved, every other IX will return the same. 

On the other hand X is not registered with container with any lifetime manager. If you resolve X it will be resolved with transient lifetime manager.

If you want X to be singleton you need to change registration into:
```C#
container.RegisterType<X>("x", new ContainerControlledLifetimeManager());
container.RegisterType<IX, X>("x");

var x = container.Resolve<X>("x");
Console.WriteLine(x == container.Resolve<X>("x"));
```
This change is due to this [bug fix](https://github.com/unitycontainer/container/releases/tag/5.2.1.235).

**Comment by tg123** [comment]
@ENikS  
will Unity have a `NotRegisteredException` in order to fail fast?

**Comment by ENikS** [comment]
But why? It is not an error that Unity can distinguish from valid case. Both of these are valid cases as far as Unity is concerned.
